AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-capybara

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Max: 15

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 20
