AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-capybara

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Max: 15

    
Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150
  Exclude:
    - test/**/*

Layout/LineLength:
  Exclude:
    - test/components/previews/**/*